<h2><i class="fa fa-home"></i> Accueil</h2>


	<?php foreach ($articleList as $article) : ?>


		<li class="post">
        <h3>
            <i class="fa fa-hand-o-right"></i>
     
            <a href="../public/oneArticle.php?id=<?= $article['id'] ?>" title="Consulter l'article">
                <?= $article['title'] ?>               
            </a>
        </h3>
        <article><?= $article['content'] ?></article>
        <br><br>
        <small>
            Rédigé par <?= $article['author_firstname'] . " " . $article['author_lastname'] ?> le <?= $article['created_at'] ?>  
        </small>
    </li>

		
	<?php endforeach; ?>
</ul>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>