<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form id="form" class="generic-form" action="processCreatePost.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title"><br>
                <em class="errorTitle" style="color: red;"></em>
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="contents" name="content" rows="15"></textarea><br>
                <em class="errorContents" style="color: red;"></em>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                    <?php foreach ($authorList as $author) : ?>
                        
                         <option value="<?= $author['id']; ?>">
                            <?= $author['firstname'] . " " . $author['lastname']; ?>
                         </option>


                     <?php endforeach; ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                        <option value="1">Jeux-Vidéos</option>
                        <option value="2">Film</option>
                        <option value="3">Sport</option>
                        <option value="4">Musique</option>
                        <option value="5">Informatique</option>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="../public/article.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form> 



<br><br><br><br><br><br><br><br><br><br>

<script src="../public/js/createPost.js"></script>