<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="processCreatePost.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="contents" name="content" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                                            <option value="1"><?= $article['author_firsname'] . $article['author_lastname'] ?></option>
                                    </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                                            <option value="2">Jeux-Vidéos</option>
                                            <option value="1">Voyages</option>
                                    </select>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>    </main>