<h2><i class="fa fa-pencil"></i> Editer cet article</h2>


<form class="generic-form" action="../public/updatePost.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li class="hideID">
                <label for="id_article">Article numéro:</label>
                <input type="text" id="id_article" name="id_article" value="<?php foreach ($articleById as $article) : ?><?= $article['id']; ?><?php endforeach; ?>">
            </li>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?php foreach ($articleById as $article) : ?><?= $article['title']; ?><?php endforeach; ?>">
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="contents" name="content" rows="15"><?php foreach ($articleById as $article) : ?><?= $article['content']; ?><?php endforeach; ?></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                    <?php foreach ($authorList as $author) : ?>
                        
                         <option value="<?= $author['id']; ?>">
                            <?= $author['firstname'] . " " . $author['lastname']; ?>
                         </option>


                     <?php endforeach; ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                        <option value="1">Jeux-Vidéos</option>
                        <option value="2">Film</option>
                        <option value="3">Sport</option>
                        <option value="4">Musique</option>
                        <option value="5">Informatique</option>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit" name="submit">Enregistrer</button>
                <a class="button button-cancel" href="../public/article.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form> 



<br><br><br><br><br><br><br><br><br><br