<h2><i class="fa fa-pencil"></i> Editer cet article</h2>


<form class="generic-form" action="../public/updatePost.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li class="">
                <label for="id_article">Article numéro: <?= $article['id']; ?></label>
                <input type="hidden" id="id_article" name="id_article" value="<?= $article['id']; ?>">
            </li>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?= $article['title']; ?>">
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="contents" name="content" rows="15"><?= $article['content']; ?></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">

                    <?php foreach ($authorList as $author) : ?>
                        
                         <option value="<?= $author['id']; ?>" 
                        <?= $author['id'] == $article['author_id'] ? 'selected' : '' ?>>
                            <?= $author['firstname'] . " " . $author['lastname']; ?>
                         </option>

                     <?php endforeach; ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                        <?php foreach ($categoryList as $category) : ?>
                        
                         <option value="<?= $category['id']; ?>" 
                        <?= $category['id'] == $article['category_id'] ? 'selected' : '' ?>>
                            <?= $category['name']; ?>
                         </option>

                     <?php endforeach; ?>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit" name="submit">Enregistrer</button>
                <a class="button button-cancel" href="../public/article.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form> 



<br><br><br><br><br><br><br><br><br><br