<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Blog</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="../public/css/main.css">
	<link rel="stylesheet" type="text/css" href="../public/css/form.css">
</head>
<body>
    <header class="blog-header">
        <h1>
        	<a href="../public/article.php"><i class="fa fa-microphone">	</i> Encore un Blog ?! #nonMaisAllo
        	</a>
        </h1>
        <nav>
            <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
        </nav>
    </header>
	<main class="container">