<br><br><br><br><br><br>
<h2><i class="fa fa-pencil"></i> Se connecter</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="../public/processLogin.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Login</legend>
        <ul>
            <li>
                <label for="email">email :</label>
                <input type="email" id="email" name="email">
            </li>
             <li>
                <label for="password">password :</label>
                <input type="password" id="password" name="password">
            </li>
                
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="../public/article.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form> 



<br><br><br><br><br><br><br><br><br><br>