<h2><i class="fa fa-home"></i> Article</h2>

 <ul>   
        
		<li class="post">
        <h3>
            <i class="fa fa-hand-o-right"></i>
                <?= clean_text($article['title']) ?>               
        </h3>
        <article><?= clean_text($article['content']) ?></article>
        <br><br>
        <small>
            Rédigé par <?= $article['author_firstname'] . " " . $article['author_lastname'] ?> le <?= $article['created_at'] ?>  
        </small>
    </li>
	
</ul>
<br><br>
<h2><i class="fas fa-comments"></i> Les commentaires</h2>
 <ul>   
    <?php foreach ($commentList as $comment) : ?>


        <li class="post">
        <h3>
            <i class="fa fa-hand-o-right"></i>
                <?= clean_text($comment['pseudo']) ?>               
        </h3>
        <article><?= clean_text($comment['content']) ?></article>
        <br><br>
        <small>
            Rédigé le <?= $comment['created_at'] ?>  
        </small>
    </li>
    <hr>
    
    <?php endforeach; ?>
</ul>
<form class="generic-form" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Postez un commentaire</legend>
        <ul>
            <li>
                <label for="pseudo">Pseudo:</label>
                <input type="text" id="Pseudo" name="pseudo"><br>
                <em class="error3" style="color: red;"></em>
            </li>
            <li>
                <label class="textarea" for="content">Commentaire :</label>
                <textarea id="contents" name="content" rows="15"></textarea><br>
                <em class="error2" style="color: red;"></em>
            </li>
            <li>
                <button class="button button-primary" type="submit" name="submit">Enregistrer</button>
            </li>
        </ul>
    </fieldset>
</form> 
<a class="return" href="../public/article.php">Retourner a la page Article</a>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<script src="../public/js/createComment.js"></script>